builds:
  - binary: blessclient
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - "-w -s -X github.com/chanzuckerberg/blessclient/pkg/util.GitSha={{.Commit}} -X github.com/chanzuckerberg/blessclient/pkg/util.Version={{.Version}} -X github.com/chanzuckerberg/blessclient/pkg/util.Dirty=false -X github.com/chanzuckerberg/blessclient/pkg/util.Release=true"

archive:
  files:
  - none*

release:
  github:
    owner: chanzuckerberg
    name: blessclient

brew:
  description: "SSH without pain."
  github:
    owner: chanzuckerberg
    name: homebrew
  homepage: "https://github.com/chanzuckerberg/blessclient"
  test: system "#{bin}/blessclient version"
