package config_test

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/chanzuckerberg/blessclient/pkg/config"
)

func TestSSHConfig(t *testing.T) {
	t.Parallel()
	a := assert.New(t)

	sshConf := &config.SSHConfig{}
	s, err := sshConf.String()
	a.Nil(err)
	a.Contains(s, "######### Generated by blessclient vundefined+undefined-dirty at")
}
