package config_test

import (
	"fmt"
	"testing"

	"github.com/chanzuckerberg/blessclient/pkg/config"
	"github.com/stretchr/testify/assert"
)

func TestSSHConfig(t *testing.T) {
	t.Parallel()
	a := assert.New(t)

	sshConf := &config.SSHConfig{
		Bastions: []config.Bastion{
			config.Bastion{},
		},
	}

	a.Equal("blessclient run", sshConf.Bastions[0].ExecCommand.String())

	s, err := sshConf.String()
	a.Nil(err)
	a.Contains(s, "######### Generated by blessclient vundefined+undefined-dirty at")
	a.Contains(s, fmt.Sprintf("exec \"blessclient run\""))
}

func TestCustomExecCommand(t *testing.T) {
	t.Parallel()
	a := assert.New(t)

	contents := "test custom exec command"
	expected := config.SSHExecCommand(contents)

	sshConf := &config.SSHConfig{
		Bastions: []config.Bastion{
			config.Bastion{
				ExecCommand: &expected,
			},
		},
	}

	// Before template
	a.Equal(contents, sshConf.Bastions[0].ExecCommand.String())

	// Template
	s, err := sshConf.String()
	a.Nil(err)
	a.Contains(s, "######### Generated by blessclient vundefined+undefined-dirty at")
	a.Contains(s, expected.String())
	a.Contains(s, fmt.Sprintf("exec \"%s\"", contents))
}
